[package]
name = "aoc2020"
version = "0.1.0"
authors = ["JonathanBrouwer"]
edition = "2018"

[profile.bench]
opt-level = 3
lto = true

[dependencies]
bit-array = "0.4.4"
typenum = "1.12.0"
rayon = "1.5.0"
scan_fmt = "0.2.5"
lazy_static = "1.4.0"
petgraph = "0.5.1"